### ISSUE TITLE
feature: save and print notification history

### ISSUE THREAD

**Issue by kristijanhusak** [folke/snacks.nvim#14]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

nvim-notify has this useful option to view history of all previously shown messages, https://github.com/rcarriga/nvim-notify#viewing-history. 

### Describe the solution you'd like

Print them in the similar fashion as `nvim-notify`, using either a command or just a method on `Snacks.notifier`.

### Describe alternatives you've considered

Probably some monkey patching, but I'd like to avoid that.

**Comment by GitMurf** [comment]
I agree. Definitely important to be able to see history. Right now I will continue to use mini.notify but when history option is added to Snacks.notifier I will switch over to this snack :-)

Initially I was staying with mini.notify due to LSP progress, but with that added today, the last thing left for me is the history :-)

Nice work as always Folke!
