### ISSUE TITLE
bug: Mini.Sessions default read using `'local'` errors when user defines default `file` config

### ISSUE THREAD

**Issue by GitMurf** [folke/snacks.nvim#144]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1108+g5a86360400

### Operating system/version

Windows 11

### Describe the bug

The default for mini.sessions errors out if the user sets the config `file` value which determines the default name for the "local" project-wide session. I recommend changing the following:

https://github.com/folke/snacks.nvim/blob/9462273bf7c0e627da0f412c02daee907947078d/lua/snacks/dashboard.lua#L744-L745

... to something like this:

```lua
    { "mini.sessions", ":lua require('mini.sessions').read()" },
    { "mini.nvim", ":lua require('mini.sessions').read()" },
```

OR

```lua
    { "mini.sessions", ":lua require('mini.sessions').read(require('mini.sessions').config.file)" },
    { "mini.nvim", ":lua require('mini.sessions').read(require('mini.sessions').config.file)" },
```

Also should be able to replace `require('mini.sessions')` with `MiniSessions` if want to make less verbose.

cc'ing @echasnovski to see if he agrees and/or has an even better default?

### Steps To Reproduce

N/A

### Expected Behavior

N/A

**Comment by echasnovski** [comment]
> Before a that session load is called, we already cd to the correct directory, so we want to load the session for the `cwd`.
> 
> I thought that was done by doing `read('local')`?

This case indeed is [configured via `config.file`](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/doc/mini-sessions.txt#L89). If you want to support only that, then using its value is the way to go indeed.

However, running `setup()` is necessary to have detected sessions, including local. And indeed running `read()` without arguments should be [the best of both worlds](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/doc/mini-sessions.txt#L132).

Ideal code snippet is something like this: `if _G.MiniSessions == nil then require('mini.sessions').setup() end; _G.MiniSessions.read()`.

**Comment by folke** [comment]
Great. Just changed it to `read()`

**Comment by GitMurf** [comment]
Thanks to both of you!

@echasnovski I hope you're proud of me that I basically got it right on the first try! 😜 🎉

**Comment by echasnovski** [comment]
> @echasnovski I hope you're proud of me that I basically got it right on the first try! 😜 🎉

Yeah, nice job :+1: ! The fact that you are checking out a dashboard which is not 'mini.starter' - not so much :thinking:

**Comment by GitMurf** [comment]
@echasnovski you know it's impossible to control the neovim urge to always test and try every new shiny object 🤣 I feel like there needs to be a Neovim Anonymous support group!

**Comment by Gaweringo** [comment]
@folke would you be open to change the implementation to the second option, which only loads sessions if they are local ones?

From [echasnovski](https://github.com/echasnovski/mini.nvim/issues/1920#issuecomment-3148346110):

> This can be done via something like this: :lua if MiniSessions == nil then require('mini.sessions').setup() end; pcall(MiniSessions.read, MiniSessions.config.file). I.e. ensure sessions are detected and try reading a local session.

So changing it to:
```lua
{ "mini.sessions", "lua if MiniSessions == nil then require('mini.sessions').setup() end; pcall(MiniSessions.read, MiniSessions.config.file)" },
{ "mini.nvim", "lua if MiniSessions == nil then require('mini.sessions').setup() end; pcall(MiniSessions.read, MiniSessions.config.file)" },
```

Because with the current implementation, choosing a folder with `Snacks.picker.projects()` or `.zoxide()` opens the last used session if there is no local one, and that session might not be related to the picked folder.

**Example:** I have a global session for `~/projects/goose` and nothing else, when I open nvim and choose for example `~/projects/duck` with `picker.projects()`, the `goose` session is read, because it was the last used / only session, although it has no relation to the picked folder.

From what it looks like, this would bring it in line with the way `neovim-session-manager` and `possession.nvim` are used:
https://github.com/folke/snacks.nvim/blob/9462273bf7c0e627da0f412c02daee907947078d/lua/snacks/dashboard.lua#L742-L743
