### ISSUE TITLE
feature: Override gitbrowse branch

### ISSUE THREAD

**Issue by dgmora** [folke/snacks.nvim#170]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When I want to copy or open the git url with gitbrowse, many times I actually want to copy the file from the `main`, not the current branch. I _think_ that's not possible with the current implementation

### Describe the solution you'd like

A way that it's easy to use gitbrowse with a specific branch.

### Describe alternatives you've considered

I considered overwritting `open`, but my branches have `/`, so it's not very practical.

**Comment by dpetka2001** [comment]
We can add a `branch` field in default options, but by default the current branch will be used as in the current implementation. You would have to call the command manually like `:lua Snacks.gitbrowse({ branch = "main" })` or whatever other branch you want. You could also map it to something like 
```lua
vim.keymap.set({ "n", "x" }, "<leader>gY", function()
  local start_line, end_line
  if vim.fn.mode() == "v" or vim.fn.mode() == "V" then
    start_line = vim.fn.line("v")
    end_line = vim.fn.line(".")
    if start_line > end_line then
      start_line, end_line = end_line, start_line
    end
  end

  -- Open command line with the function pre-filled
  local cmd = string.format(
    ':<C-u>lua Snacks.gitbrowse({  start_line = %s, end_line = %s, branch = "" })<left><left><left><left>',
    start_line or "nil",
    end_line or "nil"
  )
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(cmd, true, false, true), "n", false)
end, { desc = "Git Browse (copy)" })

```
so that your cursor goes right between the single quotes to type in the branch you want. Would that be good? 

Unfortunately, this breaks the selection of multiple lines when selecting (it will only append to the url the first line of the selection) and the only way I found around that is to calculate the visual selection in the mapping itself (and I also needed to add `start_line` and `end_line` in the default options as well). I don't know why that happens. Maybe the maintainer has a better grasp as to why this is happening.

I have something ready for this. If it's good with you, I can create a PR for this.

**Comment by dgmora** [comment]
Hey, thanks!

> We can add a branch field in default options, but by default the current branch will be used as in the current implementation. You would have to call the command manually like :lua Snacks.gitbrowse({ branch = "main" }) or whatever other branch you want

that makes sense for me. Typing the branch feels a bit overkill maybe? You can also make mistakes etc.
