### ISSUE TITLE
feature: add chunk display to Snacks.indent like https://github.com/shellRaining/hlchunk.nvim

### ISSUE THREAD

**Issue by wimstefan** [folke/snacks.nvim#230]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

No problem - just an aesthetic wishful thinking ... ;)

### Describe the solution you'd like

As described in the title I'd love to see the addition of displaying chunks in indents like [hlchunk.nvim](https://github.com/shellRaining/hlchunk.nvim).
Only if it's not a too big hassle of course.

Thank you so much for your amazing work!!!

### Describe alternatives you've considered

Until now I'm using [hlchunk.nvim](https://github.com/shellRaining/hlchunk.nvim) but if I could delete this plugin it would be one more replaced by snacks.nvim :)

**Comment by wimstefan** [comment]
Thank you so much for the lightning fast response ❣️
It looks wonderful 🤩

**Comment by gennaro-tedesco** [comment]
Can the indent module be configured to exclusively display chunks and not indent lines (I know it sounds counterintuitive since the indent module is, well, for indentation... :p). I have also been using hlchunk.nvim and have enjoyed the feature to only show chunks grouping (makes for a nicer visual for blocks with plenty of indents).

Perhaps it is possible already by setting an empty indent char?
```lua
---@type snacks.indent.Config
indent = {
  enabled = false,
  char = " ",
  only_scope = true,
  only_current = true,
},
```
the above however still shows the normal indent char nevertheless (and still works for all scopes rather than `only_scope`, unless I misunderstood the meaning of those options).

**Comment by folke** [comment]
@gennaro-tedesco done!

**Comment by gennaro-tedesco** [comment]
Wooow, that's beautiful, thank you very much!
