### ISSUE TITLE
feature: conform-like floating command input

### ISSUE THREAD

**Issue by uroybd** [folke/snacks.nvim#325]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Currently, notifer covers a lot of ground conform does. I'm using conform only for the floating command input.

### Describe the solution you'd like

An option to get such input directly from snacks.

### Describe alternatives you've considered

The alternative I considered and using is conform along with snacks.

**Comment by folke** [comment]
conform is a formatter. 
I assume you're referring to noice?
If so that is out of scope for now. Messing with `ui_attach` is a whole different beast.
And doing just the cmdline is unfortunately not possible. When you enable `cmdline` with `ui_attach`, you also need to implement `ext_popupmenu` and `ext_messages`.

**Comment by uroybd** [comment]
> conform is a formatter. I assume you're referring to noice? If so that is out of scope for now. Messing with `ui_attach` is a whole different beast. And doing just the cmdline is unfortunately not possible. When you enable `cmdline` with `ui_attach`, you also need to implement `ext_popupmenu` and `ext_messages`.

My bad. Noice.

Thank you for the clarification.
